[versions]
androidGradlePlugin = "8.1.3"
kotlin = "1.9.22"

[plugins]
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
android-application = { id = "com.android.application", version.ref = "androidGradlePlugin" }

[bundles]
